[package]
name = "cloud-entertainment/roact-rodux"
version = "0.5.5"
license = "Apache-2.0"
registry = "https://github.com/Cloud-Entertainment/wally-index"
realm = "shared"
exclude = ["wally.exe"]

[dependencies]
Roact = "core-packages/roact-compat@17.0.1-rc.16.1"
Rodux = "cloud-entertainment/rodux@4.0.3"